version: '3.9'

services:

  nginx:
    # need to use intel cpu
    platform: linux/amd64
    image: nginx:latest
    restart: "${RESTART_POLICY:-no}"
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "./nginx/${NGINX_CONFIG_FILE:-setup.conf}:/etc/nginx/conf.d/default.conf:ro"
      - "/var/www/spexo/.well-known:/var/www/react/.well-known"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
      - "django-static:/django/static_root:ro"


  mysqlDB:
    image: mysql:8.1
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-password}"
      MYSQL_DATABASE: "spexodisks"
    ports:
      - "3306:3306"
    volumes:
      # store data in a volume on the host for the MySQL database
      - type: bind
        source: ./mysql/local
        target: /var/lib/mysql
      # initialize the database from existing files in this directory
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
    restart: "${RESTART_POLICY:-no}"

  backend:
    # need to use intel cpu
    platform: linux/amd64
    build:
      context: ./SpExWebsite
      args:
        DATA_RESET_UPLOAD: false # False to only upload the files once during testing
    image: ghcr.io/spexod/backend:LATEST
    restart: "${RESTART_POLICY:-no}"
    volumes:
      - "./SpExWebsite:/usr/src/app"
      # django-static is written at build time by the SpExWebsite Dockerfile
      - "django-static:/django/static_root:rw"
    environment:
      DATA_MIGRATE_FROM_STAGED: "${DATA_MIGRATE_FROM_STAGED:-false}"
      DJANGO_USE_NEW_TABLES: "${DJANGO_USE_NEW_TABLES:-true}"
      DJANGO_DEBUG: "${DJANGO_DEBUG:-true}"
    depends_on:
      - mysqlDB

  frontend:
    # need to use intel cpu
    platform: linux/amd64
    build:
      context: ./SpExo-FrontEnd
    image: ghcr.io/spexod/frontend:LATEST
    restart: "${RESTART_POLICY:-no}"


volumes:
  django-static: