version: '3.8'

services:
  backend:
    build:
      context: ./SpExWebsite
    image: https://ghcr.io/spexod/backend:latest
    pull_policy: build
  frontend:
    build:
      context: ./SpExo-FrontEnd/front-app
    image: https://ghcr.io/spexod/frontend:latest
    pull_policy: build
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./nginx/nginx-setup-deploy.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/spexo/.well-known:/var/www/react/.well-known
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
