version: '3.8'

services:
  backend:
    image: ghcr.io/spexod/backend:LATEST
    pull_policy: always
  frontend:
    image: ghcr.io/spexod/frontend:LATEST
    pull_policy: always
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./nginx/nginx-setup-deploy.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/spexo/.well-known:/var/www/react/.well-known
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
