version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/spexo/.well-known:/var/www/react/.well-known
  backend:
    build:
      context: ./SpExWebsite
    volumes:
      - ./SpExWebsite:/usr/src/app
  frontend:
    build:
      context: ./SpExo-FrontEnd
volumes:
  react_build:
