version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "./nginx/${NGINX_CONFIG_FILE:-setup.conf}:/etc/nginx/conf.d/default.conf:ro"
      - "/var/www/spexo/.well-known:/var/www/react/.well-known"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
      - "django-static:/django/static_root:ro"
    restart: "${RESTART_POLICY:-no}"
  backend:
    build:
      context: ./SpExWebsite
      args:
        DATA_RESET_UPLOAD: false # False to only upload the files once during testing
    volumes:
      - "./SpExWebsite:/usr/src/app"
      # django-static is written at build time by the SpExWebsite Dockerfile
      - "django-static:/django/static_root:rw"
    image: ghcr.io/spexod/backend:LATEST
    environment:
      DATA_MIGRATE_FROM_STAGED: "${DATA_MIGRATE_FROM_STAGED:-false}"
      DJANGO_USE_NEW_TABLES: "${DJANGO_USE_NEW_TABLES:-true}"
      DJANGO_DEBUG: "${DJANGO_DEBUG:-true}"
    restart: "${RESTART_POLICY:-no}"
  frontend:
    build:
      context: ./SpExo-FrontEnd/front-app
    image: ghcr.io/spexod/frontend:LATEST
    restart: "${RESTART_POLICY:-no}"


volumes:
  django-static:
