version: '3'

services:
  backend:
    build:
      context: ./SpExWebsite
      dockerfile: Dockerfile-testupload
    command: gunicorn SpSite.wsgi --bind 0.0.0.0:8000
  frontend:
    build:
      context: ./SpExo-FrontEnd/front-app
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/spexo/.well-known:/var/www/react/.well-known
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
