version: '3'

services:
  backend:
    build:
      context: ./SpExWebsite
    command: gunicorn SpSite.wsgi --bind 0.0.0.0:8000
  frontend:
    build:
      context: ./SpExo-FrontEnd/front-app
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./nginx/nginx-setup-deploy.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/spexo/.well-known:/var/www/react/.well-known
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
